import '@fontsource-variable/inter';
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={""}>
        {children}
      </body>
    </html>
  );
}
